dep: 'prod,dev'
reject:
  # These are peer dependencies. Updating them is usually breaking change.
  - '@blueprintjs/core'
  - '@blueprintjs/icons'
  - '@blueprintjs/select'
  - 'fifo-logger'
  - 'react'
  - 'react-dom'
