dep: 'prod,dev'
reject:
  # These are peer dependencies. Updating them is usually breaking change.
  - '@blueprintjs/core'
  - '@blueprintjs/icons'
  - '@blueprintjs/select'
  - 'fifo-logger'
  - 'react'
  - 'react-dom'
  # https://github.com/zakodium-oss/react-science/issues/1008
  - '@types/react'
  - '@types/react-dom'
